name: Deploy scatan.html to Pages
on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
    paths-ignore:
      - "scatan.drawio"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SCALA_TARGET: ./target/scala-3.3.0
    steps:
      - uses: actions/checkout@v3
      - name: Set sbt
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "sbt"
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Create artifact directory
        run: mkdir -p ./site
      - name: Build the project
        run: |
          sbt fullLinkJS
          cp -r ${SCALA_TARGET}/js ./site/scatan
      - name: Copy scatan.html
        run: cp ./scatan.html ./site/scatan.html
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          enable_jekyll: true
          keep_files: true
          commit_message: "Deploy scatan.html to Pages"
  deploy:
    environment:
      name: production
      url: ${{ steps.pages.outputs.url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v2
