name: Update doc/main

on:
  push:
    branches:
      - main

jobs:
  update-doc-main:
    name: Merge main into doc after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v2
        id: merge
        with:
          github_token: ${{ github.token }}
          source: "main"
          target: "doc"
          webhook_url: #if present add the Slack webhook
