name: Test
on:
  push:
    branches-ignore: [ 'doc', 'develop' ]
  pull_request:
    branches: [ 'develop' ]

  # to manually trigger a workflow on GitHub
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        run: sbt test

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Check scalafmt format
        run: sbt scalafmtCheckAll
